## Source image
FROM ghcr.io/ublue-os/fedora-toolbox:latest

## Files
COPY files /
COPY scripts /tmp/scripts

## Run Scripts
RUN /tmp/scripts/fedora/faster-dnf.sh && \
    /tmp/scripts/fedora/rpm.sh && \
    /tmp/scripts/fedora/vim-default-editor.sh &&
    echo test
